package com.webService.service;
import com.webService.bean.GlobalPaiedBean;
//应收单
public class BillsReceivableXml {
	
	public static String getXmlStr(GlobalPaiedBean globalPaiedBean) throws Exception {
		StringBuffer sb=new StringBuffer();
		sb.append("<?xml version='1.0' encoding='gb2312'?>");
		sb.append("<ufinterface account='develop' billtype='F0' businessunitcode='' filename='' groupcode='001' isexchange='Y' replace='Y' roottag='' sender='ERP'>");
		sb.append("<bill>");
		sb.append("<billhead>");
		sb.append("<pk_group>001</pk_group>");
		sb.append("<pk_org>0101</pk_org>");
		sb.append("<pk_financeorgid>0101</pk_financeorgid>");
		sb.append("<officialprintuser>ERPZL</officialprintuser>");
		sb.append("<officialprintdate>2017-07-05 14:36:12</officialprintdate>");
		sb.append("<pk_billtype>F0</pk_billtype>");
		sb.append("<pk_tradetype>F0-Cxx-02</pk_tradetype>");
		sb.append("<confirmuser>ERPZL</confirmuser>");
		sb.append("<src_syscode>17</src_syscode>");
		sb.append("<syscode>0</syscode>");
		sb.append("<billstatus>1</billstatus>");
		sb.append("<billdate>2017-07-05 14:36:12</billdate>");
		sb.append("<billmaker>ERPZL</billmaker>");
		sb.append("<approver>ERPZL</approver>");
		sb.append("<approvedate>2017-07-05 14:36:12</approvedate>");
		sb.append("<money>3500</money>");
		sb.append("<local_money>3500</local_money>");
		sb.append("<rate>1</rate>");
		sb.append("<effectstatus>10</effectstatus>");
		sb.append("<effectdate>2017-07-05 14:36:12</effectdate>");
		sb.append("<pk_deptid>002</pk_deptid>");
		sb.append("<pk_psndoc>010020</pk_psndoc>");
		sb.append("<customer>200064</customer>");
		sb.append("<pk_currtype>CNY</pk_currtype>");
		sb.append("<objtype>0</objtype>");
		sb.append("<scomment>9999</scomment>");
		sb.append("<def2>123</def2>");
		sb.append("<def3>1</def3>");
		sb.append("<def4>1</def4>");
		sb.append("<bodys>");
		sb.append("<item>");
		sb.append("<material>376</material>");
		sb.append("<customer>200064</customer>");
		sb.append("<postunit>");
		sb.append("</postunit>");
		sb.append("<postpricenotax>18.675195</postpricenotax>");
		sb.append("<postprice>21.85</postprice>");
		sb.append("<pausetransact>N</pausetransact>");
		sb.append("<pk_billtype>F0</pk_billtype>");
		sb.append("<billclass>ys</billclass>");
		sb.append("<pk_tradetype>F0-Cxx-02</pk_tradetype>");
		sb.append("<busidate>2017-07-05 14:26:23</busidate>");
		sb.append("<objtype>0</objtype>");
		sb.append("<direction>1</direction>");
		sb.append("<buysellflag>1</buysellflag>");
		sb.append("<pk_currtype>CNY</pk_currtype>");
		sb.append("<rate>1</rate>");
		sb.append("<pk_deptid>002</pk_deptid>");
		sb.append("<pk_psndoc>010020</pk_psndoc>");
		sb.append("<money_de>1200</money_de>");
		sb.append("<local_money_de>1200</local_money_de>");
		sb.append("<quantity_de>54.919908</quantity_de>");
		sb.append("<local_tax_de>174.36</local_tax_de>");
		sb.append("<notax_de>1025.64</notax_de>");
		sb.append("<local_notax_de>1025.64</local_notax_de>");
		sb.append("<taxrate>17</taxrate>");
		sb.append("<taxcodeid>17</taxcodeid>");
		sb.append("<invoiceno>null</invoiceno>");
		sb.append("<def11>320</def11>");
		sb.append("<def12>320</def12>");
		sb.append("<def7>882</def7>");
		sb.append("<contractno>1111</contractno>");
		sb.append("<scomment>3333</scomment>");
		sb.append("</item>");
		sb.append("</bodys>");
		sb.append("</billhead>");
		sb.append("</bill>");
		sb.append("</ufinterface>");
		String xmlMassage = sb.toString();
		return xmlMassage;
	  };
}
