/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-09-27 09:38:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    <a href=\"springmvc/testRedirect.do\">springmvc/testRedirect.do</a>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <a href=\"springmvc/testView.do\">:testView  自定义视图</a>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("  <form action=\"springmvc/testPojo.do\" method=\"post\">\r\n");
      out.write("  <br>\r\n");
      out.write("    user name:<input type=\"text\" name=\"username\"/><br>\r\n");
      out.write("    password:<input type=\"text\" name=\"password\"/><br>\r\n");
      out.write("    email:<input type=\"text\" name=\"email\"/><br>\r\n");
      out.write("    age:<input type=\"text\" name=\"age\"/><br>\r\n");
      out.write("    city:<input type=\"text\" name=\"address.city\"/><br>\r\n");
      out.write("    province:<input type=\"text\" name=\"address.province\"/><br>\r\n");
      out.write("    <input type=\"submit\"  value=\"Submit\"/>\r\n");
      out.write(" \r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("   <a href=\"springmvc/testMap.do\">处理数据模型方式2:testMap</a>\r\n");
      out.write("    <br><br>\r\n");
      out.write("     \r\n");
      out.write("      <a href =\"springmvc/testModelAndView.do\">处理数据模型方式1:testModelAndView</a>    \r\n");
      out.write("       <br><br>\r\n");
      out.write("        <br><br>\r\n");
      out.write("     <form action=\"springmvc/testRestmodel.do\" method=\"post\">\r\n");
      out.write("     <input type=\"submit\"  value=\"TestRest modleandview\" />\r\n");
      out.write("     </form>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    <form action=\"springmvc/testRest.do\" method=\"post\">\r\n");
      out.write("    <input type=\"submit\"  value=\"TestRest Post\" />\r\n");
      out.write("   </form>\r\n");
      out.write("\r\n");
      out.write("   <form action=\"springmvc/testRest/1.do\" method=\"post\">\r\n");
      out.write("     <input type=\"hidden\"  name=\"_method\"  value=\"DELETE\"/>\r\n");
      out.write("    <input type=\"submit\"  value=\"TestRest DELETE\" />\r\n");
      out.write("   </form>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <form action=\"springmvc/testRest/1.do\" method=\"post\">\r\n");
      out.write("     <input type=\"hidden\"  name=\"_method\"  value=\"PUT\"/>\r\n");
      out.write("    <input type=\"submit\"  value=\"TestRest PUT\" />\r\n");
      out.write("   </form>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    \r\n");
      out.write("   <form action=\"springmvc/testRest.do\" method=\"post\">\r\n");
      out.write("    <input type=\"submit\"  value=\"TestRest Post\" />\r\n");
      out.write("   </form>\r\n");
      out.write("   \r\n");
      out.write("    <br><br>\r\n");
      out.write("     <a href=\"testRestGet/1.do\">test Rest Get</a>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <br><br>\r\n");
      out.write("     <a href=\"testRestGet/1.do\">test Rest Get</a>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("  <a href=\"testPathVariable/1.do\">testPathVariable.do/1</a>\r\n");
      out.write("    <br><br>\r\n");
      out.write("  <a href=\"testParamAndHeaders.do?username=zhangsan&age=11\">testParamAndHeaders</a>\r\n");
      out.write("     \r\n");
      out.write(" <br><br>\r\n");
      out.write("  <form action=\"testMethod.do\" method=\"POST\"> \r\n");
      out.write("    <input type=\"submit\" value=\"submit\" />\r\n");
      out.write("    <button name=\"submit\" text=\"提交\"></button>\r\n");
      out.write("  </form>\r\n");
      out.write("  <br>\r\n");
      out.write("  <a href=\"testMethod.do\">testMethod.do</a>\r\n");
      out.write("   <br>\r\n");
      out.write("  <a href=\"testrequestmapping.do\">testrequestmapping.do</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
